let number1: number = 16;
let number2: number = 12;
let ketqua: number;
ketqua = number1 + number2;
console.log("Kết quả của phép cộng:", ketqua);
ketqua = number1 - number2;
console.log("Kết quả của phép trừ:", ketqua);
ketqua = number1 * number2;
console.log("Kết quả của phép nhân:", ketqua);
ketqua = number1 / number2;
console.log("Kết quả của phép chia:", ketqua);
